### ISSUE TITLE
Problems with angular material tables

### ISSUE THREAD

**Issue by TheDaAndy** [Independer/ng-tooltip#6]
Can't get it to work with angular material tables. When clicking on the standardicon, the popup shows up below the table and far to right. The table is inside a angular material dialog.

**Comment by hanstiono** [comment]
Hi @TheDaAndy 

Thanks for reporting. I just updated the package to `2.1.2` and that should fix the issue with the ng-tooltip inside angular material dialog.
I updated this package to be compatible with latest Angular 9, so you might need to update your Angular too and added a peerDependency to `@angular/sdk` v9.x which you also need to install.
